ignore:
  - "env"
  - "mocks"
  - "benchmarking"
  - "api/benchmarking"
  - "primitives/benchmarking"

coverage:
  precision: 2
  round: down
  range: "75..100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error
