name: Build and Run Tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/local/lib/android
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Runtime using Docker
        run: make build-docker-benchmarking
      - name: Setup GO env
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
      - name: Run Unit Tests
        run: make test